### ISSUE TITLE
Injector.get 的时候，拿到的是一个新的实例么，会不会有缓存，如果拿到的不是一个新的实例，有没有办法指定获取新的实例。

### ISSUE THREAD

**Issue by NasaRocket** [hullis/redi#11]

**Comment by hullis** [comment]
1. `get` 拿到的是缓存的实例
2. 如果想创建新的，可以使用 `createInstance` 方法，但是这个方法创建的实例不会被 `Injector` 管理，需要在销毁的时候手动调用其 `dispose` 方法
